// Mock Data for Development (Không cần backend)
// Khi setup backend xong, đổi USE_MOCK_DATA = false trong .env

// Mock Patients Data
export const mockPatients = [
  {
    id: 1,
    patient_code: 'BN000001',
    full_name: 'Nguyễn Văn An',
    phone: '0901234567',
    email: 'nguyenvanan@email.com',
    date_of_birth: '1990-01-15',
    gender: 'male',
    age: 34,
    address: '123 Đường Lê Lợi, Quận 1, TP.HCM',
    citizen_id: '001234567890',
    insurance_number: 'BH123456789',
    emergency_contact: 'Nguyễn Thị B',
    emergency_phone: '0912345678',
    blood_type: 'O+',
    allergies: 'Không có',
    medical_history: 'Tiền sử huyết áp cao',
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 2,
    patient_code: 'BN000002',
    full_name: 'Trần Thị Bích',
    phone: '0909876543',
    email: 'tranthib@email.com',
    date_of_birth: '1985-05-20',
    gender: 'female',
    age: 39,
    address: '456 Đường Nguyễn Huệ, Quận 3, TP.HCM',
    citizen_id: '009876543210',
    insurance_number: 'BH987654321',
    emergency_contact: 'Trần Văn C',
    emergency_phone: '0923456789',
    blood_type: 'A+',
    allergies: 'Dị ứng penicillin',
    medical_history: 'Đã từng phẫu thuật ruột thừa',
    created_at: '2024-01-20T10:30:00Z',
  },
  {
    id: 3,
    patient_code: 'BN000003',
    full_name: 'Lê Minh Cường',
    phone: '0918765432',
    email: 'leminhcuong@email.com',
    date_of_birth: '1995-08-10',
    gender: 'male',
    age: 29,
    address: '789 Đường Trần Hưng Đạo, Quận 5, TP.HCM',
    citizen_id: '005678901234',
    insurance_number: 'BH567890123',
    emergency_contact: 'Lê Thị D',
    emergency_phone: '0934567890',
    blood_type: 'B+',
    allergies: 'Không có',
    medical_history: 'Khỏe mạnh',
    created_at: '2024-02-01T14:15:00Z',
  },
  {
    id: 4,
    patient_code: 'BN000004',
    full_name: 'Phạm Thị Diệu',
    phone: '0927654321',
    email: 'phamthidieu@email.com',
    date_of_birth: '1988-12-25',
    gender: 'female',
    age: 35,
    address: '321 Đường Hai Bà Trưng, Quận 1, TP.HCM',
    citizen_id: '003456789012',
    insurance_number: 'BH345678901',
    emergency_contact: 'Phạm Văn E',
    emergency_phone: '0945678901',
    blood_type: 'AB+',
    allergies: 'Dị ứng hải sản',
    medical_history: 'Tiểu đường type 2',
    created_at: '2024-02-10T09:20:00Z',
  },
  {
    id: 5,
    patient_code: 'BN000005',
    full_name: 'Hoàng Văn Phong',
    phone: '0936543210',
    email: 'hoangvanphong@email.com',
    date_of_birth: '1992-03-18',
    gender: 'male',
    age: 32,
    address: '654 Đường Phan Xích Long, Quận Phú Nhuận, TP.HCM',
    citizen_id: '007890123456',
    insurance_number: 'BH789012345',
    emergency_contact: 'Hoàng Thị F',
    emergency_phone: '0956789012',
    blood_type: 'O-',
    allergies: 'Không có',
    medical_history: 'Từng bị gãy xương tay',
    created_at: '2024-02-15T11:45:00Z',
  },
];

// Mock Staff Data
export const mockStaff = [
  // Doctors
  {
    id: 1,
    staff_code: 'BS001',
    full_name: 'BS. Nguyễn Văn Khoa',
    phone: '0912345678',
    email: 'bs.khoa@healthcare.com',
    date_of_birth: '1979-05-15',
    gender: 'male',
    address: '123 Đường Lý Tự Trọng, Q1, TP.HCM',
    citizen_id: '001234567891',
    role: 'doctor',
    specialization: 'Nội khoa',
    department: 'Khoa Nội',
    license_number: 'BS123456',
    education: 'Tiến sĩ Y khoa',
    experience_years: 20,
    hire_date: '2010-01-15',
    is_active: true,
    created_at: '2010-01-15T08:00:00Z',
  },
  {
    id: 2,
    staff_code: 'BS002',
    full_name: 'BS. Trần Thị Lan',
    phone: '0923456789',
    email: 'bs.lan@healthcare.com',
    date_of_birth: '1986-08-20',
    gender: 'female',
    address: '456 Đường Nguyễn Thị Minh Khai, Q3, TP.HCM',
    citizen_id: '002345678912',
    role: 'doctor',
    specialization: 'Ngoại khoa',
    department: 'Khoa Ngoại',
    license_number: 'BS234567',
    education: 'Thạc sĩ Y khoa',
    experience_years: 12,
    hire_date: '2012-06-01',
    is_active: true,
    created_at: '2012-06-01T08:00:00Z',
  },
  {
    id: 3,
    staff_code: 'BS003',
    full_name: 'BS. Lê Minh Tuấn',
    phone: '0934567890',
    email: 'bs.tuan@healthcare.com',
    date_of_birth: '1982-03-10',
    gender: 'male',
    address: '789 Đường Võ Văn Tần, Q3, TP.HCM',
    citizen_id: '003456789123',
    role: 'doctor',
    specialization: 'Tim mạch',
    department: 'Khoa Tim mạch',
    license_number: 'BS345678',
    education: 'Tiến sĩ Y khoa',
    experience_years: 15,
    hire_date: '2011-03-20',
    is_active: true,
    created_at: '2011-03-20T08:00:00Z',
  },
  {
    id: 4,
    staff_code: 'BS004',
    full_name: 'BS. Phạm Thị Hương',
    phone: '0945678901',
    email: 'bs.huong@healthcare.com',
    date_of_birth: '1988-11-25',
    gender: 'female',
    address: '321 Đường Pasteur, Q1, TP.HCM',
    citizen_id: '004567891234',
    role: 'doctor',
    specialization: 'Da liễu',
    department: 'Khoa Da liễu',
    license_number: 'BS456789',
    education: 'Thạc sĩ Y khoa',
    experience_years: 10,
    hire_date: '2014-09-15',
    is_active: true,
    created_at: '2014-09-15T08:00:00Z',
  },
  {
    id: 5,
    staff_code: 'BS005',
    full_name: 'BS. Hoàng Văn Nam',
    phone: '0956789012',
    email: 'bs.nam@healthcare.com',
    date_of_birth: '1985-07-18',
    gender: 'male',
    address: '654 Đường Cách Mạng Tháng 8, Q10, TP.HCM',
    citizen_id: '005678912345',
    role: 'doctor',
    specialization: 'Tai Mũi Họng',
    department: 'Khoa TMH',
    license_number: 'BS567890',
    education: 'Thạc sĩ Y khoa',
    experience_years: 8,
    hire_date: '2016-01-10',
    is_active: true,
    created_at: '2016-01-10T08:00:00Z',
  },
  // Nurses
  {
    id: 6,
    staff_code: 'YT001',
    full_name: 'Y Tá Lê Thị Mai',
    phone: '0967890123',
    email: 'yta.mai@healthcare.com',
    date_of_birth: '1996-04-12',
    gender: 'female',
    address: '111 Đường Hoàng Sa, Q1, TP.HCM',
    citizen_id: '006789123456',
    role: 'nurse',
    specialization: null,
    department: 'Khoa Nội',
    license_number: 'YT123456',
    education: 'Cao đẳng Điều dưỡng',
    experience_years: 6,
    hire_date: '2018-03-01',
    is_active: true,
    created_at: '2018-03-01T08:00:00Z',
  },
  {
    id: 7,
    staff_code: 'YT002',
    full_name: 'Y Tá Nguyễn Thị Hoa',
    phone: '0978901234',
    email: 'yta.hoa@healthcare.com',
    date_of_birth: '1994-09-28',
    gender: 'female',
    address: '222 Đường Trường Sơn, Q3, TP.HCM',
    citizen_id: '007891234567',
    role: 'nurse',
    specialization: null,
    department: 'Khoa Ngoại',
    license_number: 'YT234567',
    education: 'Cao đẳng Điều dưỡng',
    experience_years: 5,
    hire_date: '2019-06-15',
    is_active: true,
    created_at: '2019-06-15T08:00:00Z',
  },
  {
    id: 8,
    staff_code: 'YT003',
    full_name: 'Y Tá Trần Văn Dũng',
    phone: '0989012345',
    email: 'yta.dung@healthcare.com',
    date_of_birth: '1997-02-05',
    gender: 'male',
    address: '333 Đường Điện Biên Phủ, Q10, TP.HCM',
    citizen_id: '008912345678',
    role: 'nurse',
    specialization: null,
    department: 'Khoa Tim mạch',
    license_number: 'YT345678',
    education: 'Cao đẳng Điều dưỡng',
    experience_years: 4,
    hire_date: '2020-02-01',
    is_active: true,
    created_at: '2020-02-01T08:00:00Z',
  },
  // Technicians
  {
    id: 9,
    staff_code: 'KTV001',
    full_name: 'KTV Vũ Minh Hải',
    phone: '0990123456',
    email: 'ktv.hai@healthcare.com',
    date_of_birth: '1993-12-14',
    gender: 'male',
    address: '444 Đường Lê Văn Sỹ, Quận 3, TP.HCM',
    citizen_id: '009123456789',
    role: 'technician',
    specialization: 'Xét nghiệm máu',
    department: 'Khoa Xét nghiệm',
    license_number: 'KTV123456',
    education: 'Cao đẳng Kỹ thuật Y học',
    experience_years: 7,
    hire_date: '2017-05-10',
    is_active: true,
    created_at: '2017-05-10T08:00:00Z',
  },
  {
    id: 10,
    staff_code: 'KTV002',
    full_name: 'KTV Đỗ Thị Lan',
    phone: '0901234560',
    email: 'ktv.lan@healthcare.com',
    date_of_birth: '1995-06-22',
    gender: 'female',
    address: '555 Đường Phan Đăng Lưu, Quận Phú Nhuận, TP.HCM',
    citizen_id: '010123456780',
    role: 'technician',
    specialization: 'Siêu âm',
    department: 'Khoa Chẩn đoán hình ảnh',
    license_number: 'KTV234567',
    education: 'Cao đẳng Kỹ thuật Y học',
    experience_years: 5,
    hire_date: '2019-08-15',
    is_active: true,
    created_at: '2019-08-15T08:00:00Z',
  },
];

// Mock Appointments Data
const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

export const mockAppointments = [
  // Today's appointments
  {
    id: 1,
    appointment_code: 'APT000001',
    patient_id: 1,
    patient_name: 'Nguyễn Văn An',
    patient_phone: '0901234567',
    doctor_id: 1,
    doctor_name: 'BS. Nguyễn Văn Khoa',
    clinic_id: 1,
    room_number: 'P101',
    room_name: 'Phòng khám Nội khoa 1',
    appointment_date: today,
    appointment_time: '08:00:00',
    status: 'completed',
    reason: 'Khám tổng quát',
    symptoms: 'Đau đầu, sốt nhẹ',
    notes: 'Bệnh nhân đã khám xong',
    created_at: '2024-03-01T10:00:00Z',
  },
  {
    id: 2,
    appointment_code: 'APT000002',
    patient_id: 2,
    patient_name: 'Trần Thị Bích',
    patient_phone: '0909876543',
    doctor_id: 2,
    doctor_name: 'BS. Trần Thị Lan',
    clinic_id: 2,
    room_number: 'P102',
    room_name: 'Phòng khám Ngoại khoa 1',
    appointment_date: today,
    appointment_time: '08:30:00',
    status: 'confirmed',
    reason: 'Tái khám sau mổ',
    symptoms: null,
    notes: null,
    created_at: '2024-03-02T14:30:00Z',
  },
  {
    id: 3,
    appointment_code: 'APT000003',
    patient_id: 3,
    patient_name: 'Lê Minh Cường',
    patient_phone: '0918765432',
    doctor_id: 1,
    doctor_name: 'BS. Nguyễn Văn Khoa',
    clinic_id: 1,
    room_number: 'P101',
    room_name: 'Phòng khám Nội khoa 1',
    appointment_date: today,
    appointment_time: '09:00:00',
    status: 'pending',
    reason: 'Khám sức khỏe định kỳ',
    symptoms: 'Không có triệu chứng',
    notes: null,
    created_at: '2024-03-03T08:00:00Z',
  },
  {
    id: 4,
    appointment_code: 'APT000004',
    patient_id: 4,
    patient_name: 'Phạm Thị Diệu',
    patient_phone: '0927654321',
    doctor_id: 3,
    doctor_name: 'BS. Lê Minh Tuấn',
    clinic_id: 1,
    room_number: 'P201',
    room_name: 'Phòng khám Tim mạch',
    appointment_date: today,
    appointment_time: '09:30:00',
    status: 'confirmed',
    reason: 'Khám tim mạch',
    symptoms: 'Đau ngực, khó thở',
    notes: null,
    created_at: '2024-03-03T10:00:00Z',
  },
  {
    id: 5,
    appointment_code: 'APT000005',
    patient_id: 5,
    patient_name: 'Hoàng Văn Phong',
    patient_phone: '0936543210',
    doctor_id: 4,
    doctor_name: 'BS. Phạm Thị Hương',
    clinic_id: 3,
    room_number: 'P301',
    room_name: 'Phòng khám Da liễu',
    appointment_date: today,
    appointment_time: '10:00:00',
    status: 'pending',
    reason: 'Khám da',
    symptoms: 'Ngứa, nổi mẩn đỏ',
    notes: null,
    created_at: '2024-03-03T11:00:00Z',
  },
  {
    id: 6,
    appointment_code: 'APT000006',
    patient_id: 1,
    patient_name: 'Nguyễn Văn An',
    patient_phone: '0901234567',
    doctor_id: 5,
    doctor_name: 'BS. Hoàng Văn Nam',
    clinic_id: 3,
    room_number: 'P201',
    room_name: 'Phòng khám TMH',
    appointment_date: today,
    appointment_time: '10:30:00',
    status: 'confirmed',
    reason: 'Khám tai mũi họng',
    symptoms: 'Đau họng, khó nuốt',
    notes: null,
    created_at: '2024-03-03T12:00:00Z',
  },
  {
    id: 7,
    appointment_code: 'APT000007',
    patient_id: 2,
    patient_name: 'Trần Thị Bích',
    patient_phone: '0909876543',
    doctor_id: 1,
    doctor_name: 'BS. Nguyễn Văn Khoa',
    clinic_id: 1,
    room_number: 'P101',
    room_name: 'Phòng khám Nội khoa 1',
    appointment_date: today,
    appointment_time: '14:00:00',
    status: 'pending',
    reason: 'Khám bệnh',
    symptoms: 'Mệt mỏi, chóng mặt',
    notes: null,
    created_at: '2024-03-03T13:00:00Z',
  },
  {
    id: 8,
    appointment_code: 'APT000008',
    patient_id: 3,
    patient_name: 'Lê Minh Cường',
    patient_phone: '0918765432',
    doctor_id: 2,
    doctor_name: 'BS. Trần Thị Lan',
    clinic_id: 2,
    room_number: 'P102',
    room_name: 'Phòng khám Ngoại khoa 1',
    appointment_date: today,
    appointment_time: '14:30:00',
    status: 'cancelled',
    reason: 'Khám ngoại khoa',
    symptoms: 'Đau bụng',
    notes: 'Bệnh nhân hủy lịch',
    created_at: '2024-03-03T13:30:00Z',
  },
  // Tomorrow's appointments
  {
    id: 9,
    appointment_code: 'APT000009',
    patient_id: 4,
    patient_name: 'Phạm Thị Diệu',
    patient_phone: '0927654321',
    doctor_id: 1,
    doctor_name: 'BS. Nguyễn Văn Khoa',
    clinic_id: 1,
    room_number: 'P101',
    room_name: 'Phòng khám Nội khoa 1',
    appointment_date: tomorrow,
    appointment_time: '08:00:00',
    status: 'confirmed',
    reason: 'Tái khám',
    symptoms: null,
    notes: null,
    created_at: '2024-03-04T08:00:00Z',
  },
  {
    id: 10,
    appointment_code: 'APT000010',
    patient_id: 5,
    patient_name: 'Hoàng Văn Phong',
    patient_phone: '0936543210',
    doctor_id: 3,
    doctor_name: 'BS. Lê Minh Tuấn',
    clinic_id: 1,
    room_number: 'P201',
    room_name: 'Phòng khám Tim mạch',
    appointment_date: tomorrow,
    appointment_time: '09:00:00',
    status: 'pending',
    reason: 'Khám tim',
    symptoms: 'Tim đập nhanh',
    notes: null,
    created_at: '2024-03-04T09:00:00Z',
  },
  // Yesterday's appointments
  {
    id: 11,
    appointment_code: 'APT000011',
    patient_id: 1,
    patient_name: 'Nguyễn Văn An',
    patient_phone: '0901234567',
    doctor_id: 2,
    doctor_name: 'BS. Trần Thị Lan',
    clinic_id: 2,
    room_number: 'P102',
    room_name: 'Phòng khám Ngoại khoa 1',
    appointment_date: yesterday,
    appointment_time: '10:00:00',
    status: 'completed',
    reason: 'Khám bệnh',
    symptoms: 'Đau lưng',
    notes: 'Đã khám xong',
    created_at: '2024-03-02T08:00:00Z',
  },
  {
    id: 12,
    appointment_code: 'APT000012',
    patient_id: 2,
    patient_name: 'Trần Thị Bích',
    patient_phone: '0909876543',
    doctor_id: 4,
    doctor_name: 'BS. Phạm Thị Hương',
    clinic_id: 3,
    room_number: 'P301',
    room_name: 'Phòng khám Da liễu',
    appointment_date: yesterday,
    appointment_time: '11:00:00',
    status: 'completed',
    reason: 'Khám da',
    symptoms: 'Mụn',
    notes: 'Đã điều trị',
    created_at: '2024-03-02T09:00:00Z',
  },
];

// Mock Clinics Data
export const mockClinics = [
  {
    id: 1,
    room_number: 'P101',
    room_name: 'Phòng khám Nội khoa 1',
    department_name: 'Khoa Nội',
    floor_number: 1,
    capacity: 2,
    is_available: true,
  },
  {
    id: 2,
    room_number: 'P102',
    room_name: 'Phòng khám Ngoại khoa 1',
    department_name: 'Khoa Ngoại',
    floor_number: 1,
    capacity: 2,
    is_available: true,
  },
  {
    id: 3,
    room_number: 'P201',
    room_name: 'Phòng khám Tai Mũi Họng',
    department_name: 'Khoa TMH',
    floor_number: 2,
    capacity: 1,
    is_available: true,
  },
];

// Mock User (for login)
export const mockUsers = [
  {
    id: 1,
    username: 'admin',
    email: 'admin@healthcare.com',
    password: 'admin123',
    role: 'admin',
    is_active: true,
    full_name: 'Quản trị viên',
  },
  {
    id: 2,
    username: 'doctor1',
    email: 'doctor@healthcare.com',
    password: 'doctor123',
    role: 'doctor',
    is_active: true,
    full_name: 'BS. Nguyễn Văn Khoa',
  },
  {
    id: 3,
    username: 'receptionist1',
    email: 'tieptan@healthcare.com',
    password: 'tieptan123',
    role: 'receptionist',
    is_active: true,
    full_name: 'Nguyễn Thị Bích',
  },
];

// Helper function to simulate API delay
export const delay = (ms = 500) => new Promise(resolve => setTimeout(resolve, ms));

// Helper function for pagination
export const paginate = (array, page = 1, limit = 10) => {
  const start = (page - 1) * limit;
  const end = start + limit;
  return {
    data: array.slice(start, end),
    total: array.length,
    page: parseInt(page),
    limit: parseInt(limit),
    totalPages: Math.ceil(array.length / limit),
  };
};

// Helper function for search
export const searchData = (array, searchTerm, fields = []) => {
  if (!searchTerm) return array;

  const term = searchTerm.toLowerCase();
  return array.filter(item => {
    return fields.some(field => {
      const value = item[field];
      return value && value.toString().toLowerCase().includes(term);
    });
  });
};

// Helper function for sort
export const sortData = (array, sortBy = 'id', order = 'DESC') => {
  return [...array].sort((a, b) => {
    const aVal = a[sortBy];
    const bVal = b[sortBy];

    if (order === 'ASC') {
      return aVal > bVal ? 1 : -1;
    } else {
      return aVal < bVal ? 1 : -1;
    }
  });
};
